import AddPhotoAlternateModule from "@mui/icons-material/AddPhotoAlternate";
import ArrowDropDownModule from "@mui/icons-material/ArrowDropDown";
import CancelOutlinedModule from "@mui/icons-material/CancelOutlined";
import CloudUploadModule from "@mui/icons-material/CloudUpload";
import DateRangeModule from "@mui/icons-material/DateRange";
import DeleteModule from "@mui/icons-material/Delete";
import ImageOutlinedModule from "@mui/icons-material/ImageOutlined";
import InsertDriveFileModule from "@mui/icons-material/InsertDriveFile";
import PaletteOutlinedModule from "@mui/icons-material/PaletteOutlined";
import SearchModule from "@mui/icons-material/Search";
import VisibilityModule from "@mui/icons-material/Visibility";
import VisibilityOffModule from "@mui/icons-material/VisibilityOff";
import { resolveIcon } from "./resolveIcon";

export const AddPhotoAlternate = resolveIcon(AddPhotoAlternateModule);
export const ArrowDropDown = resolveIcon(ArrowDropDownModule);
export const CancelOutlined = resolveIcon(CancelOutlinedModule);
export const CloudUpload = resolveIcon(CloudUploadModule);
export const Delete = resolveIcon(DeleteModule);
export const DateRange = resolveIcon(DateRangeModule);
export const ImageOutlined = resolveIcon(ImageOutlinedModule);
export const PaletteOutlined = resolveIcon(PaletteOutlinedModule);
export const InsertDriveFile = resolveIcon(InsertDriveFileModule);
export const Search = resolveIcon(SearchModule);
export const Visibility = resolveIcon(VisibilityModule);
export const VisibilityOff = resolveIcon(VisibilityOffModule);
