export enum FieldType {
  Text = "text",
  Email = "email",
  Phone = "phone",
  Password = "password",
  Number = "number",
  Date = "date",
  DateRange = "date-range",
  DateTime = "datetime",
  Time = "time",
  Select = "select",
  Autocomplete = "autocomplete",
  LazyAutocomplete = "lazy-autocomplete",
  Textarea = "textarea",
  RichText = "richtext",
  Image = "image",
  MultipleImage = "multiple-image",
  MultipleFile = "multiple-file",
  Code = "code",
  Checkbox = "checkbox",
  MultiCheckbox = "multi-checkbox",
  Radio = "radio",
  RadioGroup = "radio-group",
  MultiSelect = "multi-select",
  LeadLabels = "lead-labels",
  Address = "address",
  Switch = "switch",
  Currency = "currency",
  Slider = "slider",
  RangeSlider = "range-slider",
  Rating = "rating",
  EmojiText = "emoji-text",
  Color = "color",
  KeyValue = "key-value",
  KeyValueSelect = "key-value-select",
}

export const ADDRESS_TYPES_ARRAY = [
  "HOME",
  "WORK",
  "BILLING",
  "SHIPPING",
  "OFFICE",
  "WAREHOUSE",
] as const;
